name: Deploy Cloud Run
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: flexiserver
        source: .
        region: us-central1
        flags: --allow-unauthenticated